### ISSUE TITLE
HMR not working

### ISSUE THREAD

**Issue by eleach** [forge42dev/base-stack#12]
Hello,

Should Hot Module Replacement (HMR) be enabled for this project?

It is not working for me. I'm on a Mac.

If I install the base react-router:

   npx create-react-router@latest my-react-router-app

HMR does work.

Thanks.

**Comment by AlemTuzlak** [comment]
@rphlmr could this be due to hono server?

**Comment by rphlmr** [comment]
I'm not sure what is happening.

I'm also on macos

![CleanShot 2024-11-27 at 19 30 28@2x](https://github.com/user-attachments/assets/0072f8e3-ed15-4a26-944a-385f60127fca)

**Comment by AlemTuzlak** [comment]
I've just tested this in 3 different envs and works everywhere, closing the issue, if you can create a minimum repro feel free to re-open
