### ISSUE TITLE
react-router-hono-server not found

### ISSUE THREAD

**Issue by fredericoo** [forge42dev/base-stack#9]
When trying to install, getting this:

```bash
 ERR_PNPM_FETCH_404  GET https://pkg.pr.new/rphlmr/react-router-hono-server@10.tgz: Not Found - 404
```

**Comment by AlemTuzlak** [comment]
Raphael merged the PR for rr7 supoprt but hasn't released v2 yet, try with this one until then:

https://pkg.pr.new/rphlmr/react-router-hono-server@18.tgz
